name: Build Check Running

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # イメージのビルドは時間がかかるため，事前にビルドしたものをpullしてくる
      # https://hub.docker.com/r/haruarima08/etrobocon2026
      - name: Pull Docker image
        run: |
          docker pull haruarima08/etrobocon2026:arm64

      - name: Run build in container
        run: |
          docker run --rm -v $(pwd):/RasPike-ART/sdk/workspace/etrobocon2026 haruarima08/etrobocon2026:arm64 \
          bash -c "cd /RasPike-ART/sdk/workspace/etrobocon2026 && make build-running"