name: Test Running

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: make test-running
